version: "3"
services:
  app:
    container_name: memo-app-node
    restart: always
    build: .
    ports:
      - "3000:3000"
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
